# Cloudflare Pages configuration
name = "slimogroup"
compatibility_date = "2023-10-30"

# Pages build configuration
[build]
command = ""
[build.upload]
format = "directory"

# Static site configuration
[site]
bucket = "."

# Pages specific configuration
[pages]
pages_build_output_dir = "."

# Environment specific settings
[env.production]
name = "slimogroup-prod"

[env.preview]
name = "slimogroup-preview" 